shop=["milk","bread","butter","curd"]
print(shop)
shop.append("poha")
print(shop)
shop.pop()
print(shop)
shop.extend(["jam","chocolate"])
print(shop)
shop.insert(1,"laptop")
print(shop)
shop.reverse()
print(shop)
shop.sort()
print(shop)
shop.remove("jam")
print(shop)
shop.clear()
print("your shopping cart items are:",shop)